# Basic Python

## 1. Split this string

In [18]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742
print("the diameter of {0} is {1} kilometers".format(planet,diameter))

the diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [1]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
a=np.zeros(10)
print(a)
import numpy as np
a=np.ones(10)*5
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
a=[]
for i in range(20,36):
  if i%2==0:
    a.append(i)
print(a)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
g=np.concatenate((a,b),axis=0)
print(g)


TypeError: ignored

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [6]:
import pandas as pd
data={'name':['jack','john','ram'],'age':[20,30,40]}
df=pd.DataFrame(data)
df
  


name  age
0  jack   20
1  john   30
2   ram   40

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [9]:
import pandas as pd
from dateutil.parser import parse
date_series=pd.Series(['Jan 2015','Feb 2016','Mar 2017','Apr 2018','may 2019'])
print("Original series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse(' 11 ' + d))
print(result)

Original series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    may 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24